// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA50-jPgqUvPF4d1MZJuKOYO5vNuutHiyk',
    appId: '1:414422473305:web:64a053640f5ee796ed2f48',
    messagingSenderId: '414422473305',
    databaseURL: "https://attendo-312ea-default-rtdb.firebaseio.com/",  // remove this line
    projectId: 'attendo-312ea',
    authDomain: 'attendo-312ea.firebaseapp.com',
    storageBucket: 'attendo-312ea.firebasestorage.app',
    measurementId: 'G-XXDVC0WYD7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzIU9gW4qMREjtnQ91FWfamvOnP2QlK4M',
    appId: '1:414422473305:android:d042f039ee277ba1ed2f48',
    messagingSenderId: '414422473305',
    projectId: 'attendo-312ea',
    storageBucket: 'attendo-312ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbriSZUoI7ENYYLeDCEyW4DlsdTleLW3w',
    appId: '1:414422473305:ios:b5f531f526b3d184ed2f48',
    messagingSenderId: '414422473305',
    projectId: 'attendo-312ea',
    storageBucket: 'attendo-312ea.firebasestorage.app',
    iosBundleId: 'com.example.attendo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbriSZUoI7ENYYLeDCEyW4DlsdTleLW3w',
    appId: '1:414422473305:ios:b5f531f526b3d184ed2f48',
    messagingSenderId: '414422473305',
    projectId: 'attendo-312ea',
    storageBucket: 'attendo-312ea.firebasestorage.app',
    iosBundleId: 'com.example.attendo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA50-jPgqUvPF4d1MZJuKOYO5vNuutHiyk',
    appId: '1:414422473305:web:10642ec000e55ee8ed2f48',
    messagingSenderId: '414422473305',
    projectId: 'attendo-312ea',
    authDomain: 'attendo-312ea.firebaseapp.com',
    storageBucket: 'attendo-312ea.firebasestorage.app',
    measurementId: 'G-TNKWRBC97B',
  );
}
